name: Continuous Integration
on: [push, pull_request]
jobs:
  ci:
    name: Linting and tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the branch
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Run clj-kondo
        uses: DeLaGuardo/clojure-lint-action@master
        with:
          clj-kondo-args: --lint src
          check-name: clj-kondo report
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Install leiningen
        uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.4
      - run: lein test
