name: Continuous Integration
on: [push, pull_request]
jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the branch
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Run clj-kondo
        uses: DeLaGuardo/clojure-lint-action@master
        with:
          clj-kondo-args: --lint src
          check-name: clj-kondo report
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Leiningen, with Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 9, 10, 11]
    steps:
      - name: Install leiningen
        uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.5
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: lein test

  clojure-cli-test:
    name: Clojure CLI, with Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 9, 10, 11]
    steps:
      - name: Checkout the branch
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Install Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Install Clojure CLI
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.10.1.763'
      - run: clojure -M:test:runner
